add command to openldap container
jp-gouin/helm-openldap pull request #194
Opened 2024-09-10 08:29 UTC by davidfrickert

this command ensures non-first openldap containers dont try to init already initialized cluster-wide resources, such as the root DN or ppolicy module.

- more detail: https://github.com/jp-gouin/helm-openldap/issues/148#issuecomment-2338435733

### What this PR does / why we need it:

### Pre-submission checklist:

* [ ] Did you explain what problem does this PR solve? Or what new features have been added?
* [ ] Have you updated the readme?
* [ ] Is this PR backward compatible? **If it is not backward compatible, please discuss open a ticket first**

2024-09-10 08:30 UTC, davidfrickert commented
potentially fixes #148 

the list of env vars that are removed is non exhaustive, maybe more need to be added, these are just the ones that were causing problems in my setup

2024-10-01 06:52 UTC, jp-gouin commented
Hi @davidfrickert ,
The CI has been fixed in main, can you sync your PR ?

2024-10-02 12:53 UTC, Arano-kai requested changes

2024-10-02 12:59 UTC, Arano-kai commented on templates/statefulset.yaml
> +              /opt/bitnami/scripts/openldap/entrypoint.sh /opt/bitnami/scripts/openldap/run.sh
This is bitnami-specific and fail on custom container.
Either we postulate that only bitnami/openldap is supported, or check that things in place before calls.

2024-10-02 13:19 UTC, Arano-kai commented on templates/statefulset.yaml
> +              /opt/bitnami/scripts/openldap/entrypoint.sh /opt/bitnami/scripts/openldap/run.sh
Also, the `/opt/bitnami/scripts/openldap/run.sh` is actually default `CMD` (`args` in k8s manifest), so highly recommend change:
* fom `/opt/bitnami/scripts/openldap/entrypoint.sh /opt/bitnami/scripts/openldap/run.sh`
* to `exec /opt/bitnami/scripts/openldap/entrypoint.sh`

That will avoid overwriting default or user-supplied args.

2024-10-15 15:46 UTC, davidfrickert commented on templates/statefulset.yaml
> +              /opt/bitnami/scripts/openldap/entrypoint.sh /opt/bitnami/scripts/openldap/run.sh
hey, just came back from vacation will try to resolve these issues this or next week

2024-11-06 13:59 UTC, davidfrickert commented on values.yaml
> +    if [ "$host" = "{{ template "openldap.fullname" . }}-0" ]
eh this won't work unfortunately

2024-11-06 14:22 UTC, davidfrickert commented on templates/statefulset.yaml
> +              /opt/bitnami/scripts/openldap/entrypoint.sh /opt/bitnami/scripts/openldap/run.sh
> Also, the `/opt/bitnami/scripts/openldap/run.sh` is actually default `CMD` (`args` in k8s manifest), so highly recommend change:
> 
>     * fom `/opt/bitnami/scripts/openldap/entrypoint.sh /opt/bitnami/scripts/openldap/run.sh`
> 
>     * to `exec /opt/bitnami/scripts/openldap/entrypoint.sh`
> 
> 
> That will avoid overwriting default or user-supplied args.

hmm `exec /opt/bitnami/scripts/openldap/entrypoint.sh` does not seem to work 
--> /opt/bitnami/scripts/openldap/entrypoint.sh: line 14: $1: unbound variable

(from latest commit on this PR)

2024-11-06 18:21 UTC, Arano-kai commented on values.yaml
> +    if [ "$host" = "{{ template "openldap.fullname" . }}-0" ]
Currently, command and args passed as is.
This may work with special handling from template side by `common.tplvalues.merge` or similar.
I'll check and place additional commit for this.

2024-11-06 18:26 UTC, Arano-kai commented on values.yaml
> +    if [ "$host" = "{{ template "openldap.fullname" . }}-0" ]
Also bash is supported (actually my last commit to bitnami/containers/openldap incorporate bash-specific functionality), just replace `- sh` by `- /bin/bash`

2024-11-07 10:59 UTC, davidfrickert commented on templates/statefulset.yaml
> +              /opt/bitnami/scripts/openldap/entrypoint.sh /opt/bitnami/scripts/openldap/run.sh
i might be missing something but can't get it to work, i removed the args empty list so it isn't getting used but still get the same error (checked with helm template and the args are not overwritten)

an `echo "$@"` also prints empty

2024-11-07 11:02 UTC, davidfrickert commented on templates/statefulset.yaml
> +              /opt/bitnami/scripts/openldap/entrypoint.sh /opt/bitnami/scripts/openldap/run.sh
I guess overriding the container command also resets args?

2024-11-07 11:02 UTC, davidfrickert commented on values.yaml
> +    if [ "$host" = "{{ template "openldap.fullname" . }}-0" ]
ah i see. usually if i see `sh` being used i assume `bash` is not available

2024-11-07 11:10 UTC, davidfrickert commented on templates/statefulset.yaml
> +              /opt/bitnami/scripts/openldap/entrypoint.sh /opt/bitnami/scripts/openldap/run.sh
yeah okay i was just inspecting the bitnami/openldap container and this is what came up:

```
            "Cmd": [
                "/opt/bitnami/scripts/openldap/run.sh"
            ],
            "ArgsEscaped": true,
            "Image": "",
            "Volumes": null,
            "WorkingDir": "",
            "Entrypoint": [
                "/opt/bitnami/scripts/openldap/entrypoint.sh"
            ],
```

And https://stackoverflow.com/questions/44316361/difference-between-docker-entrypoint-and-kubernetes-container-spec-command

> If you supply a command for a Container, only the supplied command is used. The default EntryPoint and the default Cmd defined in the Docker image are ignored. Your command is run with the args supplied (or no args if none supplied).

2025-01-17 04:37 UTC, closed without merging